name: innbyggers-flate PR deploy
on:
  pull_request:
    paths:
      - 'apps/innbyggers-flate/**'
      - 'shared-config/**'
      - 'package.json'
      - '.github/workflows/innbyggers-flate-pr-deploy.yaml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-frontend
        with:
          node_auth_token: ${{ secrets.READER_TOKEN }}
      - run: pnpm build:demo --filter=innbyggers-flate
      - uses: navikt/frontend/actions/spa-deploy/v2@main
        with:
          app: amt-deltaker-innbyggers-flate
          team: amt
          source: apps/innbyggers-flate/build
          ingress: https://amt-deltaker-innbyggers-flate-pr-${{ github.event.number }}.ekstern.dev.nav.no
          environment: dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  comment-link-to-app:
    if: github.event.action == 'opened'
    permissions:
      pull-requests: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            URL for testing av innbyggers-flate: https://amt-deltaker-innbyggers-flate-pr-${{ github.event.number }}.ekstern.dev.nav.no
